import { Department, Employee, EmployeeSkill, Client, Site, Project, Task } from './types';

export const mockDepartments: Department[] = [
  { id: 'd1', name: 'Executive', description: 'Leadership team' },
  { id: 'd2', name: 'Operations', description: 'Operations management' },
  { id: 'd3', name: 'Field Operations', description: 'HVAC field supervisors' },
  { id: 'd4', name: 'Service', description: 'HVAC technicians' },
  { id: 'd5', name: 'Dispatch', description: 'Scheduling and customer coordination' },
];

export const mockEmployees: Employee[] = [
  {
    id: 'e1',
    employee_code: 'SPC001',
    aadhar_number: '111122223333',
    first_name: 'Priya',
    last_name: 'Raman',
    name: 'Priya Raman',
    date_of_birth: '1985-05-12',
    gender: 'FEMALE',
    email: 'priya@supercoolhvac.local',
    phone: '9000000001',
    address: 'Head Office, MG Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    postal_code: '560001',
    hire_date: '2020-01-10',
    employment_status: 'ACTIVE',
    department_id: 'd1',
    department_name: 'Executive',
    job_title: 'CEO',
    title: 'CEO',
    department: 'Executive',
    daily_wage: 9000,
    daily_incentive_earned: 1500,
    service_area: 'All zones',
    availability: 'AVAILABLE',
    status: 'ACTIVE'
  },
  {
    id: 'e2',
    employee_code: 'SPC002',
    aadhar_number: '222233334444',
    first_name: 'Omar',
    last_name: 'Khan',
    name: 'Omar Khan',
    date_of_birth: '1988-11-20',
    gender: 'MALE',
    email: 'omar@supercoolhvac.local',
    phone: '9000000002',
    address: 'Operations Office',
    city: 'Bengaluru',
    state: 'Karnataka',
    postal_code: '560002',
    hire_date: '2021-03-15',
    employment_status: 'ACTIVE',
    department_id: 'd2',
    department_name: 'Operations',
    manager_id: 'e1',
    job_title: 'MANAGER',
    title: 'Operations Manager',
    department: 'Operations',
    daily_wage: 5500,
    daily_incentive_earned: 900,
    service_area: 'All zones',
    availability: 'AVAILABLE',
    status: 'ACTIVE'
  },
  {
    id: 'e3',
    employee_code: 'SPC003',
    aadhar_number: '333344445555',
    first_name: 'Maya',
    last_name: 'Kapoor',
    name: 'Maya Kapoor',
    date_of_birth: '1991-03-15',
    gender: 'FEMALE',
    email: 'maya@supercoolhvac.local',
    phone: '9000000003',
    address: 'North Zone Office',
    city: 'Bengaluru',
    state: 'Karnataka',
    postal_code: '560003',
    hire_date: '2022-04-12',
    employment_status: 'ACTIVE',
    department_id: 'd3',
    department_name: 'Field Operations',
    manager_id: 'e2',
    job_title: 'SUPERVISOR',
    title: 'HVAC Supervisor',
    department: 'Field Operations',
    service_area: 'North Zone',
    daily_wage: 3500,
    daily_incentive_earned: 500,
    availability: 'AVAILABLE',
    status: 'ACTIVE'
  },
  {
    id: 'e4',
    employee_code: 'SPC004',
    aadhar_number: '444455556666',
    first_name: 'Arjun',
    last_name: 'Mehta',
    name: 'Arjun Mehta',
    date_of_birth: '1993-07-25',
    gender: 'MALE',
    email: 'arjun@supercoolhvac.local',
    phone: '9000000004',
    address: 'Central Zone Depot',
    city: 'Bengaluru',
    state: 'Karnataka',
    postal_code: '560004',
    hire_date: '2023-02-01',
    employment_status: 'ACTIVE',
    department_id: 'd4',
    department_name: 'Service',
    manager_id: 'e3',
    job_title: 'SENIOR_TECHNICIAN',
    title: 'Senior HVAC Technician',
    department: 'Service',
    service_area: 'Central Zone',
    daily_wage: 2800,
    daily_incentive_earned: 400,
    plate_number: 'KA-01-HV-1201',
    make: 'Tata',
    model: 'Ace',
    year: 2024,
    availability: 'AVAILABLE',
    status: 'ACTIVE'
  },
  {
    id: 'e5',
    employee_code: 'SPC005',
    aadhar_number: '555566667777',
    first_name: 'Lina',
    last_name: 'Fernandes',
    name: 'Lina Fernandes',
    date_of_birth: '1995-09-05',
    gender: 'FEMALE',
    email: 'lina@supercoolhvac.local',
    phone: '9000000005',
    address: 'Dispatch Center',
    city: 'Bengaluru',
    state: 'Karnataka',
    postal_code: '560005',
    hire_date: '2023-08-07',
    employment_status: 'ACTIVE',
    department_id: 'd5',
    department_name: 'Dispatch',
    manager_id: 'e2',
    job_title: 'DISPATCHER',
    title: 'Dispatcher',
    department: 'Dispatch',
    service_area: 'All zones',
    daily_wage: 1800,
    daily_incentive_earned: 250,
    availability: 'AVAILABLE',
    status: 'ACTIVE'
  },
  {
    id: 'e6',
    employee_code: 'SPC006',
    aadhar_number: '666677778888',
    first_name: 'Dev',
    last_name: 'Iyer',
    name: 'Dev Iyer',
    date_of_birth: '1997-12-14',
    gender: 'MALE',
    email: 'dev@supercoolhvac.local',
    phone: '9000000006',
    address: 'South Zone Depot',
    city: 'Bengaluru',
    state: 'Karnataka',
    postal_code: '560006',
    hire_date: '2024-01-20',
    employment_status: 'ACTIVE',
    department_id: 'd4',
    department_name: 'Service',
    manager_id: 'e3',
    job_title: 'TECHNICIAN',
    title: 'HVAC Technician',
    department: 'Service',
    service_area: 'South Zone',
    daily_wage: 2200,
    daily_incentive_earned: 300,
    plate_number: 'KA-01-HV-1202',
    make: 'Mahindra',
    model: 'Bolero Pickup',
    year: 2023,
    availability: 'AVAILABLE',
    status: 'ACTIVE'
  }
];

export const mockEmployeeSkills: EmployeeSkill[] = [
  {
    id: 's1',
    employee_id: 'e1',
    skill_name: 'HVAC business operations',
    skill_level: 'EXPERT',
    certificate_number: 'CERT-OPS-0001',
    issuing_authority: 'HVAC Leadership Board',
    issue_date: '2021-01-15'
  },
  {
    id: 's2',
    employee_id: 'e2',
    skill_name: 'Field operations planning',
    skill_level: 'EXPERT',
    certificate_number: 'CERT-OPS-1001',
    issuing_authority: 'HVAC Safety Board',
    issue_date: '2021-06-10'
  },
  {
    id: 's3',
    employee_id: 'e3',
    skill_name: 'Commercial HVAC',
    skill_level: 'EXPERT',
    certificate_number: 'CERT-HVAC-1001',
    issuing_authority: 'HVAC Safety Board',
    issue_date: '2022-05-20'
  },
  {
    id: 's4',
    employee_id: 'e4',
    skill_name: 'AC repair',
    skill_level: 'EXPERT',
    certificate_number: 'CERT-HVAC-2001',
    issuing_authority: 'EPA Training Partner',
    issue_date: '2023-02-18'
  },
  {
    id: 's5',
    employee_id: 'e4',
    skill_name: 'Electrical diagnostics',
    skill_level: 'ADVANCED',
    certificate_number: 'CERT-ELEC-2002',
    issuing_authority: 'Electrical Safety Board',
    issue_date: '2023-04-09'
  },
  {
    id: 's6',
    employee_id: 'e5',
    skill_name: 'Dispatch coordination',
    skill_level: 'ADVANCED',
    certificate_number: 'CERT-DISP-3001',
    issuing_authority: 'Customer Operations Academy',
    issue_date: '2023-09-05'
  },
  {
    id: 's7',
    employee_id: 'e6',
    skill_name: 'Preventive maintenance',
    skill_level: 'INTERMEDIATE',
    certificate_number: 'CERT-HVAC-4001',
    issuing_authority: 'EPA Training Partner',
    issue_date: '2024-02-12'
  }
];

export const mockClients: Client[] = [
  {
    id: 'c1',
    client_name: 'Ravi Shah',
    client_type: 'Corporate',
    industry: 'Real Estate Developer',
    gst_number: '29AAAAA1111A1Z1',
    website: 'https://metroplaza.local',
    head_office_address: '22 Market Road, Bengaluru, Karnataka, 560010',
    primary_contact_name: 'Ravi Shah',
    designation: 'Managing Director',
    mobile: '9888800001',
    email: 'ravi@metroplaza.local',
    decision_maker: 'Yes',
    accounts_contact: 'Finance Team (accounts@metroplaza.local)',
    lead_source: 'Referral',
    client_status: 'ACTIVE',
    notes: 'Premium commercial landlord. Owns multiple plazas.',

    // Backwards compatibility fields
    client_code: 'C001',
    company_name: 'Metro Plaza',
    address: '22 Market Road, Bengaluru',
    project_name: 'Rooftop HVAC Replacement',
    location: 'Metro Plaza Rooftop',
    building_type: 'COMMERCIAL',
    approx_area: '45,000 sq ft',
    requirement: 'NEW_INSTALLATION',
    preferred_hvac_system: 'PACKAGE_UNIT',
    current_challenges: 'Existing rooftop unit has weak cooling and frequent compressor trips.',
    budget_range: 'INR 15L - 20L',
    expected_completion_date: '2026-08-15'
  },
  {
    id: 'c2',
    client_name: 'Nisha Rao',
    client_type: 'Residential Association',
    industry: 'Real Estate Association',
    gst_number: '29BBBBB2222B2Z2',
    website: 'https://greenfield.local',
    head_office_address: '14 Lake View Street, Bengaluru, Karnataka, 560011',
    primary_contact_name: 'Nisha Rao',
    designation: 'Association President',
    mobile: '9888800002',
    email: 'nisha@greenfield.local',
    decision_maker: 'Yes',
    accounts_contact: 'Treasurer (treasurer@greenfield.local)',
    lead_source: 'Website',
    client_status: 'ACTIVE',
    notes: 'Residential society with 120+ split AC installations.',

    // Backwards compatibility fields
    client_code: 'C002',
    company_name: 'Greenfield Apartment Association',
    address: '14 Lake View Street, Bengaluru',
    project_name: 'Annual Maintenance Contract',
    location: 'Greenfield Apartments',
    building_type: 'RESIDENTIAL',
    approx_area: '120 apartments',
    requirement: 'AMC',
    preferred_hvac_system: 'SPLIT_AC',
    current_challenges: 'Common-area AC units need scheduled preventive maintenance.',
    budget_range: 'INR 3L - 5L',
    expected_completion_date: '2026-07-31'
  }
];

export const mockSites: Site[] = [
  {
    id: 's1',
    site_code: 'S001',
    client_id: 'c1',
    client_name: 'Metro Plaza',
    site_name: 'Metro Plaza Rooftop',
    customer_name: 'Metro Plaza',
    contact_person: 'Ravi Shah',
    contact_phone: '9888800001',
    contact_email: 'facilities@metroplaza.local',
    address: '22 Market Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    postal_code: '560010',
    site_type: 'COMMERCIAL',
    property_type: 'Retail complex',
    service_zone: 'Central Zone',
    landmark: 'Near City Metro Station',
    access_instructions: 'Use service lift B. Security pass required.',
    preferred_visit_time: '10 AM - 5 PM',
    equipment_summary: 'Two rooftop packaged units, lobby split AC units, AHU room on terrace.',
    assigned_manager_id: 'e3',
    status: 'ACTIVE',

    // New SiteDetails fields
    pincode: '560010',
    site_contact_person: 'Ravi Shah',
    mobile: '9888800001',
    email: 'facilities@metroplaza.local',
    total_area: '45,000 Sq.Ft',
    number_of_floors: '6',
    existing_hvac: 'VRF / Rooftop Packaged',
    existing_brand: 'Daikin / Carrier',
    existing_capacity: '120 HP / 50 TR',
    amc_required: 'Yes'
  },
  {
    id: 's2',
    site_code: 'S002',
    client_id: 'c2',
    client_name: 'Greenfield Apartment Association',
    site_name: 'Greenfield Apartments',
    customer_name: 'Greenfield Apartment Association',
    contact_person: 'Nisha Rao',
    contact_phone: '9888800002',
    contact_email: 'admin@greenfield.local',
    address: '14 Lake View Street',
    city: 'Bengaluru',
    state: 'Karnataka',
    postal_code: '560011',
    site_type: 'RESIDENTIAL',
    property_type: 'Apartment complex',
    service_zone: 'North Zone',
    landmark: 'Opposite Lake Park',
    access_instructions: 'Visitor entry at gate 2. Coordinate apartment access with security.',
    preferred_visit_time: '9 AM - 1 PM',
    equipment_summary: 'Common-area split AC systems and clubhouse ducted unit.',
    assigned_manager_id: 'e3',
    status: 'ACTIVE',

    // New SiteDetails fields
    pincode: '560011',
    site_contact_person: 'Nisha Rao',
    mobile: '9888800002',
    email: 'admin@greenfield.local',
    total_area: '180,000 Sq.Ft',
    number_of_floors: '12 (3 Towers)',
    existing_hvac: 'Multi Split / Cassette / High-wall Unit',
    existing_brand: 'Voltas / Mitsubishi',
    existing_capacity: '185 TR Cumulative',
    amc_required: 'Yes'
  }
];

export const mockProjects: Project[] = [
  {
    id: 'p1',
    name: 'Rooftop Unit Repair',
    customer_name: 'Metro Plaza',
    service_address: '22 Market Road, Central Zone',
    equipment_type: 'Rooftop packaged unit',
    job_type: 'REPAIR',
    description: 'Diagnose weak cooling and unusual compressor noise on the main rooftop unit.',
    status: 'IN_PROGRESS',
    start_date: '2026-06-01',
    owner_id: 'e4'
  },
  {
    id: 'p2',
    name: 'Preventive Maintenance Visit',
    customer_name: 'Greenfield Apartments',
    service_address: '14 Lake View Street, North Zone',
    equipment_type: 'Split AC systems',
    job_type: 'MAINTENANCE',
    description: 'Quarterly preventive maintenance for lobby and common-area split AC units.',
    status: 'SCHEDULED',
    start_date: '2026-07-01',
    owner_id: 'e3'
  }
];

export const mockTasks: Task[] = [
  {
    id: 't1',
    title: 'Inspect compressor and contactor',
    description: 'Check compressor amp draw, contactor wear, and wiring condition.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    due_date: '2026-06-24',
    project_id: 'p1',
    assignee_id: 'e4'
  },
  {
    id: 't2',
    title: 'Clean condenser coil',
    description: 'Clean debris from the condenser coil and verify airflow.',
    status: 'REVIEW',
    priority: 'MEDIUM',
    due_date: '2026-06-22',
    project_id: 'p1',
    assignee_id: 'e6'
  },
  {
    id: 't3',
    title: 'Prepare refrigerant pressure report',
    description: 'Record suction and discharge pressures after the repair check.',
    status: 'TODO',
    priority: 'URGENT',
    due_date: '2026-06-21',
    project_id: 'p1',
    assignee_id: 'e3'
  },
  {
    id: 't4',
    title: 'Schedule apartment unit access',
    description: 'Coordinate access windows with building management and residents.',
    status: 'TODO',
    priority: 'LOW',
    due_date: '2026-07-08',
    project_id: 'p2',
    assignee_id: 'e5'
  }
];
